baseURL = 'https://jbas-research.github.io/website/'
languageCode = 'en'
title = 'JBas'

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
  # LoveIt theme version
  version = "0.2.X"
   
[menu]
  [[menu.main]]
    identifier = "About"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "About"
    url = "/About/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "CV"
    pre = ""
    post = ""
    name = "CV"
    url = "/CV/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "Scientific_Production"
    pre = ""
    post = ""
    name = "Scientific_Production"
    url = "/Scientific_Production/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "Contact"
    pre = ""
    post = ""
    name = "Contact"
    url = "/Contact/"
    title = ""
    weight = 4

# Home page config
  [params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = "JBas"
      # subtitle shown in home page
      subtitle = "This site is still under construction, but you can check the menu or contact me for more information."
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
      # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false

  [params.social]
  Email = "j.bas.research@gmail.com"
